#pragma once
 
#include "ScriptMacro.h"
#include "BTScript.h"
 
#define Z_BT_USimpleCodeEvent 

#define BT_FileID_UEProject_TestSlate_EditorExtension_Plugins_BlueprintTool_Source_BlueprintToolCode_Public_SimpleCodeEvent_h_12_GENERATED_BODY_BT \
Z_BT_USimpleCodeEvent

#undef CURRENT_FILE_ID_BT
#define CURRENT_FILE_ID_BT BT_FileID_UEProject_TestSlate_EditorExtension_Plugins_BlueprintTool_Source_BlueprintToolCode_Public_SimpleCodeEvent_h
#undef NEWLINE
#define NEWLINE 12
